### ISSUE TITLE
Where to obtain "license_keys"?

### ISSUE THREAD

**Issue by CatChenal** [JohnSnowLabs/nlu#100]
All the colab examples I wanted to run [e.g. this one](https://colab.research.google.com/github/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Healthcare/3.Clinical_Entity_Resolvers.ipynb) are asking for a license file via `files.upload()`.
How do I obtain one?
Thanks.

**Comment by C-K-Loan** [comment]
Hi @CatChenal 
you can obtain license keys from here https://www.johnsnowlabs.com/install/

**Comment by CatChenal** [comment]
Thanks.
