### ISSUE TITLE
Remove the hard dependency on the pyspark

### ISSUE THREAD

**Issue by alexott** [JohnSnowLabs/nlu#19]
Right now, the `nlu` package has a hard dependency on the `pyspark` making it hard to use with Databricks runtime, or other compatible Spark runtime. Instead, this package should either rely on implicit dependency completely, or use something like [findspark package](https://github.com/minrk/findspark), something like done [here](https://github.com/holdenk/spark-testing-base/blob/master/python/sparktestingbase/utils.py).

P.S. the spark-nlp package itself doesn't depend on the pyspark

**Comment by C-K-Loan** [comment]
Hi @alexott  that is a great idea! 
This will be integrated into NLU 1.0.5

**Comment by C-K-Loan** [comment]
This is taken care of now 
https://github.com/JohnSnowLabs/nlu/releases/tag/v1.0.5

**Comment by alexott** [comment]
thank you!
