### ISSUE TITLE
Issue with nlu.load('sentiment')

### ISSUE THREAD

**Issue by janevlee** [JohnSnowLabs/nlu#33]
I'm trying to follow the example at nlu/examples/colab/component_examples/sequence2sequence/translation_demo.ipynb but I keep on getting this error when nlu.load('sentiment').

My code:
```python
import nlu 
nlu.load('sentiment').predict('I love NLU! <3') 
```

My error:
```python
analyze_sentiment download started this may take some time.
Approx size to download 4.9 MB
[OK!]
<class 'pyspark.sql.utils.IllegalArgumentException'>
'Unsupported class file major version 55'
Something went wrong during loading and fitting the pipe. Check the other prints for more information and also verbose mode. Did you use a correct model reference?
<nlu.NluError at 0x7f046d214be0>
```

**Comment by maziyarpanahi** [comment]
Hi,
`'Unsupported class file major version 55'` this is a very popular error in Apache Spark. You either don't have Java 8 or you don't have it as default. (probably you have a newer version of Java in your path. The requirement is Java 8 - Python 3.6/3.7)

**Comment by janevlee** [comment]
Thanks
