### ISSUE TITLE
Embed Japanese Sentences with Bert

### ISSUE THREAD

**Issue by Weile0409** [JohnSnowLabs/nlu#85]
Hi, thanks for such convenience tool! I would like to ask authors, does this tool supply 'Embed Japanese Sentences with Bert' ? Thank you

**Comment by ahmedlone127** [comment]
you might wanna take a look at this :https://nlp.johnsnowlabs.com/2021/09/16/bert_base_japanese_ja.html or this https://nlp.johnsnowlabs.com/2021/09/09/japanese_cc_300d_ja.html

**Comment by Weile0409** [comment]
Oh I see, thank you very much :)
