### ISSUE TITLE
Could not locate executable null\bin\winutils.exe

### ISSUE THREAD

**Issue by luiztauffer** [JohnSnowLabs/nlu#9]
Hi, thanks for the package, I'm starting t explore it and it looks good so far!
I've juts faced some minor issues when trying to run it on my windows machine and thought about giving a heads up here in case someone finds similar problem.

First is you need to run your python as admin, because folders are created (in order to store downloaded models I presume) and it will cause errors if no permission is granted. Is there a way to choose where these models are downloaded to? This might help with that

Second, after the installations steps in the instructions I got this error when trying to run nlu:
```
Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
```
I found the answer to this problem here: https://stackoverflow.com/a/50430966/11483674

**Comment by C-K-Loan** [comment]
Hu @luiztauffer,
thank you very much for your feedback and for sharing your experience!

Right now you cannot change the download folder for the models, but we will look into adding this in the future.


We will begin testing this issue and trying to automatically resolve it in the future.

**Comment by luiztauffer** [comment]
Hi @C-K-Loan , thanks for the reply and the update on docs. I'll close the Issue, since this seems to resolve the problem.
I think that stackoverflow reply should be referenced in your docs, if you're using it exactly as it is.

**Comment by C-K-Loan** [comment]
You are kinda right, 

but I did minor modifications and I don't want to clutter the docs with links to other pages if they just need to read out 5 lines of text.
